general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session    # Лучше использовать системный вызов
    after_sleep_cmd = niri msg action power-on-monitors
}

# 1. Сначала приглушаем свет (2 мин)
listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10 && brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -r && brightnessctl -rd rgb:kbd_backlight
}

# 2. Блокируем экран (5 мин)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 3. Выключаем монитор (6 мин)
listener {
    timeout = 360
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors 
}

# 4. Сон (10 мин)
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
